server:
  port: 8000

spring:
  application:
    name: api-gateway
     
service:
  protocol: http

    
eureka:
  client:
    serviceUrl:
     #defaultZone: http://localhost:8888/eureka/
     defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8888}/eureka/